# Generated by Django 6.1 on 2026-08-08 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('category', models.CharField(blank=True, help_text='مثلا: سرور، هاست، ایمیل، بانک، شبکه اجتماعی ...', max_length=100, verbose_name='دسته\u200cبندی')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت کلی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
            ],
            options={
                'verbose_name': 'آیتم',
                'verbose_name_plural': 'آیتم\u200cها',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='مثلا: SSH، پنل مدیریت، دیتابیس، FTP ...', max_length=100, verbose_name='عنوان بخش')),
                ('url', models.CharField(blank=True, max_length=500, verbose_name='لینک / آدرس')),
                ('username', models.CharField(blank=True, max_length=200, verbose_name='نام کاربری')),
                ('password', models.CharField(blank=True, max_length=500, verbose_name='رمز عبور')),
                ('extra', models.TextField(blank=True, help_text='هر فیلد دیگری، مثلا پورت، کلید API، توضیحات ...', verbose_name='اطلاعات اضافه')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='vault.entry', verbose_name='آیتم')),
            ],
            options={
                'verbose_name': 'بخش',
                'verbose_name_plural': 'بخش\u200cها',
                'ordering': ['order', 'id'],
            },
        ),
    ]
