# Generated by Django 6.1 on 2026-08-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='notes',
            field=models.TextField(blank=True, verbose_name='یادداشت کلی'),
        ),
    ]
