# Generated by Django 6.1 on 2026-08-08 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_section_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='notes',
        ),
    ]
